In [53]:
import pandas as pd

dataset = pd.read_csv('train.csv',index_col=0)

In [54]:
dataset.head()

,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
id,,,,,,,,,,,,,,,,,,,,,
1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,0.001953,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,0.000000,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,0.000000,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,0.013672,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,0.000000,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [55]:
dataset.shape

(990, 193)

In [56]:
dataset.describe()

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
count,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,...,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000
mean,0.017412,0.028539,0.031988,0.023280,0.014264,0.038579,0.019202,0.001083,0.007167,0.018639,...,0.036501,0.005024,0.015944,0.011586,0.016108,0.014017,0.002688,0.020291,0.008989,0.019420
std,0.019739,0.038855,0.025847,0.028411,0.018390,0.052030,0.017511,0.002743,0.008933,0.016071,...,0.063403,0.019321,0.023214,0.025040,0.015335,0.060151,0.011415,0.039040,0.013791,0.022768
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.001953,0.001953,0.013672,0.005859,0.001953,0.000000,0.005859,0.000000,0.001953,0.005859,...,0.000000,0.000000,0.000977,0.000000,0.004883,0.000000,0.000000,0.000000,0.000000,0.000977
50%,0.009766,0.011719,0.025391,0.013672,0.007812,0.015625,0.015625,0.000000,0.005859,0.015625,...,0.004883,0.000000,0.005859,0.000977,0.012695,0.000000,0.000000,0.003906,0.002930,0.011719
75%,0.025391,0.041016,0.044922,0.029297,0.017578,0.056153,0.029297,0.000000,0.007812,0.027344,...,0.043701,0.000000,0.022217,0.009766,0.021484,0.000000,0.000000,0.023438,0.012695,0.029297
max,0.087891,0.205080,0.156250,0.169920,0.111330,0.310550,0.091797,0.031250,0.076172,0.097656,...,0.429690,0.202150,0.172850,0.200200,0.106450,0.578130,0.151370,0.375980,0.086914,0.141600

In [57]:
dataset['species'].value_counts()

Alnus_Cordata                  10
Ulmus_Bergmanniana             10
Quercus_Pontica                10
Quercus_Vulcanica              10
Acer_Saccharinum               10
Quercus_Crassipes              10
Quercus_Castaneifolia          10
Crataegus_Monogyna             10
Quercus_Hartwissiana           10
Callicarpa_Bodinieri           10
Lithocarpus_Cleistocarpus      10
Quercus_Pubescens              10
Quercus_Texana                 10
Quercus_Suber                  10
Quercus_Phellos                10
Tilia_Platyphyllos             10
Acer_Palmatum                  10
Quercus_Brantii                10
Morus_Nigra                    10
Salix_Fragilis                 10
Quercus_Greggii                10
Quercus_Phillyraeoides         10
Pterocarya_Stenoptera          10
Acer_Capillipes                10
Quercus_Pyrenaica              10
Quercus_Crassifolia            10
Castanea_Sativa                10
Sorbus_Aria                    10
Tilia_Tomentosa                10
Eucalyptus_Glaucescens         10
                               ..
Quercus_x_Hispanica            10
Quercus_Kewensis               10
Quercus_Infectoria_sub         10
Acer_Pictum                    10
Quercus_Ilex                   10
Cytisus_Battandieri            10
Quercus_Canariensis            10
Cornus_Chinensis               10
Ilex_Aquifolium                10
Phildelphus                    10
Ginkgo_Biloba                  10
Cercis_Siliquastrum            10
Ilex_Cornuta                   10
Alnus_Rubra                    10
Acer_Rubrum                    10
Betula_Austrosinensis          10
Quercus_Dolicholepis           10
Liquidambar_Styraciflua        10
Quercus_Chrysolepis            10
Prunus_X_Shmittii              10
Quercus_Ellipsoidalis          10
Quercus_Nigra                  10
Betula_Pendula                 10
Celtis_Koraiensis              10
Quercus_Rhysophylla            10
Olea_Europaea                  10
Rhododendron_x_Russellianum    10
Acer_Rufinerve                 10
Zelkova_Serrata                10
Quercus_Variabilis             10
Name: species, Length: 99, dtype: int64

In [58]:
import sklearn.linear_model as lm

In [59]:
lgr = lm.LogisticRegression(multi_class = 'multinomial', solver = 'newton-cg')

In [61]:
y = dataset.species

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
if y.dtype == object:
    y = le.fit_transform(y)
else:
    pass

In [62]:
X = dataset.drop('species', axis=1)
X = (dataset.ix[:,1:].values).astype('float32')

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
#X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state = 0)
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits = 1, test_size=0.2, random_state=0)
sss.get_n_splits(X, y)
X_train = []
X_test = []
for train_index, test_index in sss.split(X, y):    
    X_train, X_test, y_train, y_test = (X[train_index], X[test_index], y[train_index], y[test_index])

In [66]:
lgr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [67]:
from sklearn.metrics import log_loss

In [68]:
y_predicted = lgr.predict_proba(X_test)
if y_predicted.dtype == object:
    y_predicted = le.fit_transform(y_predicted)
else:
    pass

In [69]:
logLoss = log_loss(y_test, y_predicted)

In [70]:
print("Log Loss from multinomial logistics regression = " + str(logLoss))

Log Loss from multinomial logistics regression = 4.17477778834526

In [71]:
test_dataset = pd.read_csv('test.csv',index_col=0)

In [72]:
y_test_dataset = dataset.species

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
if y_test_dataset.dtype == object:
    y_test_dataset = le.fit_transform(y)
else:
    pass

X_test_dataset = dataset.drop('species', axis=1)
X_test_dataset = (dataset.ix[:,1:].values).astype('float32')

In [73]:
y_pred_test = lgr.predict_proba(X_test_dataset)
log_loss_test = log_loss(y_test_dataset,y_pred_test)
print("log loss for the test data using Multinomial regression= " + str(log_loss_test))

log loss for the test data using Multinomial regression= 4.154733675898927